name: coffee_inctrementer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.3.0
  freezed: ^3.2.4
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  internet_connection_checker: ^3.0.1
  dio: ^5.9.0
  cloud_firestore: ^6.1.1
  flutter_launcher_icons: ^0.14.4
  dartz: ^0.10.1
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  firebase_auth: ^6.1.4
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/app-icon.png'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed_annotation: ^3.1.0
  build_runner: ^2.10.5
  injectable_generator: ^2.11.1
  json_serializable: ^6.11.4

flutter:
  uses-material-design: true
  assets:
    - assets/app-icon.png
